### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Bokoa** [Bokoa/goldensunrise_html5#1]
- [ ] Cambiar el mapeado de eventos para que funcione con el nuevo programa
- [ ] Añadir dialogos a un npc (hay uno dentro de una casa)
- [ ] Añadir 2 nuevos botones (Start y A)
- [ ] Crear menú
